on: [workflow_call]
name: Appium Flutter Integration Server
jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1
          channel: 'stable'
      - run: |
          cd demo-app
          dart pub global activate rps --version 0.8.0
          flutter build apk --debug
          cd android && ./gradlew app:assembleDebug -Ptarget=`pwd`/../integration_test/appium.dart
      - name: "List files"
        continue-on-error: true
        run: |
          ls -l ${{ github.workspace }}/demo-app/build/app/outputs/apk/debug/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android build
          path: ${{ github.workspace }}/demo-app/build/app/outputs/apk/debug/app-debug.apk
  iOS:
    runs-on: macos-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          path: 'server'
          repository: AppiumTestDistribution/appium-flutter-server
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1
          channel: 'stable'
      - run: |
          ls
          cd server/demo-app
          flutter build ios integration_test/appium.dart  --simulator
      - name: "List files"
        continue-on-error: true
        run: |
          ls -l ${{ github.workspace }}/server/demo-app/build/ios/iphonesimulator/
      - name: "Zip files"
        run: |
          cd ${{ github.workspace }}/server/demo-app/build/ios/iphonesimulator/
          zip -r ios.zip Runner.app
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ${{ github.workspace }}/server/demo-app/build/ios/iphonesimulator/ios.zip
  macOS:
    runs-on: macos-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          path: 'server'
          repository: AppiumTestDistribution/appium-flutter-server
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1
          channel: 'stable'
      - run: |
          ls
          cd server/demo-app
          flutter build macos --debug integration_test/appium.dart
      - name: "List files"
        continue-on-error: true
        run: |
          ls -l ${{ github.workspace }}/server/demo-app/build/macos/Build/Products/Debug/
      - name: "Zip files"
        run: |
          cd ${{ github.workspace }}/server/demo-app/build/macos/Build/Products/Debug/
          zip -r macos.zip appium_testing_app.app
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ${{ github.workspace }}/server/demo-app/build/macos/Build/Products/Debug/macos.zip
